config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'admin/index'
  get 'index/index'
  	scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
	  resources :abouts
	  resources :activity, only: :show
	  resources :products, only: :show
	  resources :partners, only: [:index, :show]
	  resources :contacts
	end  
  root to: "index#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	has_one_attached :image
	has_many_attached :images
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :activitycontents
	has_one_attached :image
	has_many_attached :images
end

app/models/activitycontent.rb
class Activitycontent < ApplicationRecord
	has_one_attached :image	
  belongs_to :activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carousel.rb
class Carousel < ApplicationRecord
	has_one_attached :image	
end

app/models/partner.rb
class Partner < ApplicationRecord
	has_one_attached :image
	has_many_attached :images
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :productcontents
	has_one_attached :image
	has_many_attached :images
end

app/models/productcontent.rb
class Productcontent < ApplicationRecord
	has_one_attached :image		
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController	
  def index
  	if current_user
  		redirect_to '/admin'
  	end	
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />    
<div class="container nav"> 
  <% if current_user %>
  <%= link_to "Выход", destroy_user_session_path, method: :delete, :class => "btn btn-dark" %>
<% else %>
  <p><%= link_to "Вход", new_user_session_path, :class => "btn btn-primary" %></p>  
<% end %>
</div>

app/views/index/index.html.erb
<section class="slider1 cid-sqUhtftfxs" id="slider1-v">
    
    <div class="carousel slide" id="sqUvboAHsk" data-interval="5000">
        <ol class="carousel-indicators">
            <li data-slide-to="0" class="active" data-target="#sqUvboAHsk"></li>
            <li data-slide-to="1" data-target="#sqUvboAHsk"></li>
            <li data-slide-to="2" data-target="#sqUvboAHsk"></li>
            <li data-slide-to="3" data-target="#sqUvboAHsk"></li>
            <li data-slide-to="4" data-target="#sqUvboAHsk"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item slider-image item active">
                <div class="item-wrapper">
                    <img class="d-block w-100" src="/assets/images/mbr-1900x1267.jpg" data-slide-to="0">
                    
                    <div class="carousel-caption">
                        <h5 class="mbr-section-subtitle mbr-fonts-style display-5"><strong>СТРОИТЕЛЬСТВО</strong></h5>
                        
                    </div>
                </div>
            </div>
            <% @carousel.each do |slide| %>
            <div class="carousel-item slider-image item">
                <div class="item-wrapper">
                    <%= image_tag slide.image %>
                    
                    <div class="carousel-caption">
                        <h5 class="mbr-section-subtitle mbr-fonts-style display-5">
                        <strong>
                        <%= "#{slide.ru}" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                        <%= "#{slide.ru}" if params[:locale] == 'ru' %>
                        <%= "#{slide.en}" if params[:locale] == 'en' %>
                        <%= "#{slide.tm}" if params[:locale] == 'tm' %>
                            
                        </strong></h5>
                        
                    </div>
                </div>
            </div>
            <% end %>
            
            
        </div>
        <a class="carousel-control carousel-control-prev" role="button" data-slide="prev" href="#sqUvboAHsk">
            <span class="mobi-mbri mobi-mbri-arrow-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control carousel-control-next" role="button" data-slide="next" href="#sqUvboAHsk">
            <span class="mobi-mbri mobi-mbri-arrow-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>

<section class="content14 cid-sqTGy6amTw mbr-parallax-background" id="content14-r">
    
    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(255, 255, 255);"></div>
    
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-12">
                <% @abouts.each do |about| %>
                    <h1 class="mbr-section-title mbr-fonts-style mb-4 display-5"><strong>
                        
                        <%= simple_format about.name_ru, :style => "font-size: 2.75rem; font-family: 'Jost', sans-serif; font-weight: bold" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                        <%= simple_format about.name_ru, :style => "font-size: 2.75; font-family: 'Jost', sans-serif; font-weight: bold" if params[:locale] == 'ru' %>
                        <%= simple_format about.name_en, :style => "font-size: 2.75; font-family: 'Jost', sans-serif; font-weight: bold" if params[:locale] == 'en' %>
                        <%= simple_format about.name_tm, :style => "font-size: 2.75; font-family: 'Jost', sans-serif; font-weight: bold" if params[:locale] == 'tm' %>

                    </strong></h1>
                <ul class="list mbr-fonts-style display-7">
                    <div>
                        
                    
                        <%= simple_format about.ru_body, :style => "font-size: 22px; font-family: 'Jost', sans-serif; line-height: 1.5;" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                        <%= simple_format about.ru_body, :style => "font-size: 22px; font-family: 'Jost', sans-serif; line-height: 1.5;" if params[:locale] == 'ru' %>
                        <%= simple_format about.en_body, :style => "font-size: 22px; font-family: 'Jost', sans-serif; line-height: 1.5;" if params[:locale] == 'en' %>
                        <%= simple_format about.tm_body, :style => "font-size: 22px; font-family: 'Jost', sans-serif; line-height: 1.5;" if params[:locale] == 'tm' %>
                    <% end %>
                    
                </div>
        </div>
    </div>
</section>

<section class="gallery2" id="gallery2-m" style="background-image: url('/images/5084287.jpg')">
    <br><br>
    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2" style="color: white"><strong><em><%= t('index.partners') %></em></strong></h3>
    <br><br>        
   <div class="container">
    <div class="row">
        <% @partners.each do |partner| %>
        <div class="col-4">
            <div class="card shadow-lg p-3 mb-5 bg-body rounded" style="width: 250px">
                <p align="center"><%= image_tag partner.image, style: "width: 180px; height: 150px"%></p>
                <div class="card-body">
                    <h5 align="center" class="card-title" style="height: 30px">
                        <%= "#{partner.name_ru}" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                        <%= "#{partner.name_ru}" if params[:locale] == 'ru' %>
                        <%= "#{partner.name_en}" if params[:locale] == 'en' %>
                        <%= "#{partner.name_tm}" if params[:locale] == 'tm' %>

                    </h5>   
                </div>  
            </div>
        </div>
        <% end %>
    </div>
</div>
</section>

<section class="form5 cid-sqUdPtIqyQ" id="form5-u">
    
    <div class="mbr-overlay"></div>
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong><em><%= t('index.write') %></em></strong></h3>
            
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form action="https://mobirise.eu/" method="POST" class="mbr-form form-with-styler" data-form-title="Form Name"><input type="hidden" name="email" data-form-email="true" value="Ni5SswMm3g4AVqNN1VLglsB8edM8aDxBE+Bpj056lVoPMeeqF8kllAp7/TOWBcu5jSA4JmJHlqE4UcKRggq33foucr9OL77K8zquVUFIY7YZ4bUBtvifnDz+mTkzdpA5">
                    <div class="row">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out
                            the form!</div>
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">Oops...! some
                            problem!</div>
                    </div>
                    <div class="dragArea row">
                        <div class="col-md col-sm-12 form-group" data-for="name">
                            <input type="text" name="name" placeholder="<%= t('form.name')%>" data-form-field="name" class="form-control" value="" id="name-form5-u">
                        </div>
                        <div class="col-md col-sm-12 form-group" data-for="email">
                            <input type="email" name="email" placeholder="E-mail" data-form-field="email" class="form-control" value="" id="email-form5-u">
                        </div>
                        
                        <div class="col-12 form-group" data-for="textarea">
                            <textarea name="textarea" placeholder="<%= t('form.message')%>" data-form-field="textarea" class="form-control" id="textarea-form5-u"></textarea>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn">
                            <button type="submit" class="btn btn-primary display-4" style="width: 150px"><%= t('index.send') %></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="footer5 cid-sqTKvdBvWV" once="footers" id="footer5-s">

    

    

    <div class="container">
        <div class="media-container-row">
            <div class="col-md-1 col-6">
                <div class="media-wrap">
                    <a href="https://mobirise.co/">
                        <img src="/assets/images/-1-121x125.png" alt="Mobirise">
                    </a>
                </div>
            </div>
            <div class="col-11 col-6">
                <p class="mbr-text align-right links mbr-fonts-style display-7">
                    <a href="#" class="text-black">About</a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#" class="text-black">Terms</a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#" class="text-black">Careers</a> &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#" class="text-black">Contact</a>
                </p>
            </div>
        </div>
        <!-- <div class="media-container-row">
            <div class="col-md-12"> -->
        <div class="footer-lower">
            <div class="media-container-row">
                <div class="col-md-12">
                    <hr>
                </div>
            </div>
            <div class="media-container-row">
                <div class="col-md-6 copyright">
                    <p class="mbr-text mbr-fonts-style display-7">
                        
                    </p>
                </div>
                <div class="col-md-6">
                    
                </div>
            </div>
            <!-- </div>
            </div> -->
        </div>

    </div>
</section><section id="top-1" hidden><a href="https://mobirise.site"></a>
<script src="/assets/web/assets/jquery/jquery.min.js"></script>  
<script src="/assets/popper/popper.min.js"></script>  
<script src="/assets/tether/tether.min.js"></script>  
 
<script src="/assets/smoothscroll/smooth-scroll.js"></script>  
<script src="/assets/viewportchecker/jquery.viewportchecker.js"></script>  
 
<script src="/assets/touchswipe/jquery.touch-swipe.min.js"></script>  
<script src="/assets/parallax/jarallax.min.js"></script>  
<script src="/assets/formstyler/jquery.formstyler.js"></script>  
<script src="/assets/formstyler/jquery.formstyler.min.js"></script>  
<script src="/assets/datepicker/jquery.datetimepicker.full.js"></script>  
<script src="/assets/theme/js/script.js"></script>  
<script src="/assets/formoid/formoid.min.js"></script>  
  
  
 <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HEÝKELLI DIÝAR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all' %>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

  <link rel="shortcut icon" href="/assets/images/-1-121x125.png" type="image/x-icon">

  <link rel="stylesheet" href="/assets/web/assets/mobirise-icons2/mobirise2.css">
  <link rel="stylesheet" href="/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/assets/animatecss/animate.css">
  <link rel="stylesheet" href="/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/assets/formstyler/jquery.formstyler.css">
  <link rel="stylesheet" href="/assets/formstyler/jquery.formstyler.theme.css">
  <link rel="stylesheet" href="/assets/datepicker/jquery.datetimepicker.min.css">
  <link rel="stylesheet" href="/assets/socicon/css/styles.css">
  <link rel="stylesheet" href="/assets/theme/css/style.css">
  <link rel="preload" as="style" href="/assets/mobirise/css/mbr-additional.css">
  <link rel="stylesheet" href="/assets/mobirise/css/mbr-additional.css" type="text/css">

<script src="/assets/web/assets/jquery/jquery.min.js"></script>  
<script src="/assets/popper/popper.min.js"></script>  
<script src="/assets/tether/tether.min.js"></script>  
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>  
<script src="/assets/smoothscroll/smooth-scroll.js"></script>  
<script src="/assets/viewportchecker/jquery.viewportchecker.js"></script>  
<script src="/assets/dropdown/js/nav-dropdown.js"></script>  
<script src="/assets/dropdown/js/navbar-dropdown.js"></script>  
<script src="/assets/touchswipe/jquery.touch-swipe.min.js"></script>  
<script src="/assets/parallax/jarallax.min.js"></script>  
<script src="/assets/formstyler/jquery.formstyler.js"></script>  
<script src="/assets/formstyler/jquery.formstyler.min.js"></script>  
<script src="/assets/datepicker/jquery.datetimepicker.full.js"></script>  
<script src="/assets/theme/js/script.js"></script>  
<script src="/assets/formoid/formoid.min.js"></script>   



  </head>

  <body>
  <section class="menu cid-s48OLK6784" once="menu" id="menu1-h">
    
    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <%= link_to root_path  do %>
                      <%= image_tag "/assets/images/-1-121x125.png", :style => "height: 8rem;" %>
                    <% end %>
                </span>
                <span class="navbar-caption-wrap"><%= link_to "HEYKELLI DIYAR", root_path, :class => "navbar-caption text-white text-primary display-5" %></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                  <li class="nav-item">
                    <%= link_to root_path + '#content14-r', :class => "nav-link link text-white text-primary display-4" do %>
                      
                      <%= t('layout.about') %>
                    <% end %>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link link text-white text-primary dropdown-toggle display-4" href="#" aria-expanded="true" data-toggle="dropdown-submenu"><%= t('layout.activity') %></a>
                    <div class="dropdown-menu">
                      <% @activities.each do |link| %>
                        <%= link_to "#{link.name_ru}", activity_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                        <%= link_to "#{link.name_ru}", activity_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'ru' %>
                        <%= link_to "#{link.name_en}", activity_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'en' %>
                        <%= link_to "#{link.name_tm}", activity_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'tm' %>
                      <% end %>  
                    </div>
                  </li>
                   <li class="nav-item dropdown">
                    <a class="nav-link link text-white text-primary dropdown-toggle display-4" href="#" aria-expanded="true" data-toggle="dropdown-submenu"><%= t('layout.trade') %></a>
                    <div class="dropdown-menu">
                      <% @products.each do |link| %>
                      <%= link_to "#{link.name_ru}", product_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] != true and params[:locale] != 'en' and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                      <%= link_to "#{link.name_ru}", product_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'ru' %>
                      <%= link_to "#{link.name_en}", product_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'en' %>
                      <%= link_to "#{link.name_tm}", product_path(link), :class => "text-white text-primary dropdown-item display-4" if params[:locale] == 'tm' %>
                      <% end %>
                    </div>
                  </li>
                  <li class="nav-item">
                    <%= link_to root_path + '#gallery2-m', :class => "nav-link link text-white text-primary display-4" do %>
                      
                      <%= t('layout.partners') %>
                    <% end %>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link link text-white text-primary dropdown-toggle display-4" href="#" aria-expanded="false" data-toggle="dropdown-submenu"><%= t('layout.connect') %></a>
                    <div class="dropdown-menu">
                    <%= link_to root_path + '#form5-u', :class => "text-white text-primary dropdown-item display-4" do %><%= t('layout.write') %>
                    <% end %>
                    <%= link_to new_contact_path, :class => "text-white text-primary dropdown-item display-4" do %><%= t('layout.contacts') %>
                    <% end %>
              <li class="nav-item dropdown">
                        <a class="nav-link link text-white text-primary dropdown-toggle display-4" href="#" aria-expanded="false" data-toggle="dropdown-submenu">
                          <span class="socicon socicon-internet mbr-iconfont mbr-iconfont-btn " style="font-size: 28px;"></span>
                        </a>

                      <div class="dropdown-menu">
                        
                      <%= link_to url_for(locale: :tm), :class => "btn" do %> 
                          <%= image_tag "/images/tm.png", style: "width: 25px" %><p style="color: white"><b>TM</b></p>
                      <% end %>
                      
                        
                      <%= link_to url_for(locale: :en), :class => "btn" do %>
                          <%= image_tag "/images/en.png", style: "width: 25px" %><p style="color: white"><b>EN</b></p>
                      <% end %>
                      
                      
                      <%= link_to url_for(locale: :ru), :class => "btn" do %>
                          <%= image_tag "/images/ru.png", style: "width: 25px" %><p style="color: white"><b>RU</b></p>
                      <% end %> 
                       
                     
                    </div>
                  </li>
                </ul>
                
                
            </div>
        </div>
    </nav>

</section>

    <%= yield %>

  </body>
</html>
  